"""empty message

Revision ID: bfcc926adc9e
Revises: ee360371fdd7
Create Date: 2020-09-26 14:54:42.714606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcc926adc9e'
down_revision = 'ee360371fdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('fmw', sa.Text(), nullable=False),
    sa.Column('fmd', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('fmw', sa.Text(), nullable=False),
    sa.Column('fmd', sa.Integer(), nullable=False),
    sa.Column('clearance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnel_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('am_status', sa.Text(), nullable=False),
    sa.Column('am_remarks', sa.Text(), nullable=False),
    sa.Column('pm_status', sa.Text(), nullable=False),
    sa.Column('pm_remarks', sa.Text(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personnel_status')
    op.drop_table('user')
    op.drop_table('personnel')
    # ### end Alembic commands ###
