"""empty message

Revision ID: ee360371fdd7
Revises: 9230b53fc655
Create Date: 2020-09-26 00:52:13.315138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee360371fdd7'
down_revision = '9230b53fc655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('participant', 'facilitator', 'oc', name='memberrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_type_id'], ['status_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_member',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('is_default_group', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'member_id')
    )
    op.create_table('group_status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('clearance', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('default_group_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('password', sa.Text(), nullable=False))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.create_foreign_key(None, 'user', 'group', ['default_group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    op.drop_column('user', 'event_id')
    op.drop_column('user', 'default_group_id')
    op.drop_column('user', 'clearance')
    op.drop_table('member_status_log')
    op.drop_table('group_status_log')
    op.drop_table('group_member')
    op.drop_table('group')
    op.drop_table('status')
    op.drop_table('family')
    op.drop_table('status_type')
    op.drop_table('member')
    op.drop_table('event')
    # ### end Alembic commands ###
